name: Release surrealdb-core

run-name: "Release surrealdb-core"

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  release-branch:
    name: Publish surrealdb-core crate
    runs-on: ubuntu-latest
    steps:
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          ref: e4fbb9d94af36a4c2d8dd6b077e32096f9931401

      - name: Prepare patch branch
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          set -x

          cd core
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git tag -a v1.1.1-surrealdb-core -m "Release surrealdb-core v1.1.1"
          git push --tags
          cargo publish
