name: Release surrealdb-core

run-name: "Release surrealdb-core ${{ inputs.version }} from ${{ inputs.branch }}"

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: "The version to realease, e.g. 1.1.3"
      branch:
        required: true
        type: string
        description: "The branch to publish from"

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  release-branch:
    name: Publish surrealdb-core crate
    runs-on: ubuntu-latest
    steps:
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Prepare patch branch
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          set -x

          cd core
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git tag -a v${{ inputs.version }}-surrealdb-core -m "Release surrealdb-core v${{ inputs.version }}"
          git push --tags
          cargo publish
